http:
  bind: '0.0.0.0'
  port: 8080
  domain: localhost
  enable_monitor: true

logging:
  default:
    level: debug
    file: /var/log/go_collect/default.jsonl
    console: true

database:
  username: postgres
  password: postgres
  database: go_collect
  host: localhost
  port: 5432
  time_zone: UTC
  ssl_mode: disable
  conn_max_idle_time: 30s
  conn_max_lifetime: 5m
  conn_max_idle: 10
  conn_max_opened: 100

redis:
  host: redis
  port: 6379
  username: ''
  password: ''
  session:
    db: 1
  csrf:
    db: 2
  queue:
    db: 3

session:
  expiration: 2h
  lookup: go_collect_id
  cookie_path: /
  secure: false


csrf:
  expiration: 2h
  lookup_key: X-XSRF-TOKEN
  cookie_name: XSRF-TOKEN
  cookie_path: /
  secure: false

cors:
  headers:
    - Content-Type
    - Accept
    - X-Requested-With
    - Authorization
    - Content-Length
    - X-XSRF-TOKEN
  origins:
    - '*'
  methods:
    - GET
    - POST
    - PUT
    - DELETE
