version: '3.9'

volumes:
  postgres:

networks:
  net:
    driver: bridge
    name: grpc_test

services:
  redis:
    image: 'redis:6-alpine'
    networks:
      - net
    restart: unless-stopped
    ports:
      - '6379:6379'
  postgres:
    image: postgres:14
    ports:
      - '5432:5432'
    networks:
      - net
    restart: unless-stopped
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: go_collect
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
    volumes:
      - postgres:/var/lib/postgresql/data
    shm_size: 1gb